# Generated by Django 4.2.5 on 2023-11-05 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('travelling', 'Travelling'), ('music', 'Music'), ('sports', 'Sports'), ('reading', 'Reading'), ('movies', 'Movies'), ('cooking', 'Cooking'), ('gaming', 'Gaming'), ('photography', 'Photography'), ('dancing', 'Dancing'), ('painting', 'Painting'), ('gardening', 'Gardening'), ('writing', 'Writing'), ('fishing', 'Fishing'), ('shopping', 'Shopping'), ('hiking', 'Hiking'), ('camping', 'Camping'), ('running', 'Running'), ('swimming', 'Swimming'), ('cycling', 'Cycling'), ('yoga', 'Yoga'), ('meditation', 'Meditation'), ('singing', 'Singing'), ('acting', 'Acting'), ('learning', 'Learning'), ('volunteering', 'Volunteering'), ('socializing', 'Socializing'), ('eating', 'Eating'), ('drinking', 'Drinking'), ('sleeping', 'Sleeping'), ('partying', 'Partying'), ('clubbing', 'Clubbing'), ('gambling', 'Gambling'), ('working', 'Working'), ('studying', 'Studying')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('plan', models.CharField(blank=True, choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='free', max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('finished', models.BooleanField(choices=[(False, 'Incomplete'), (True, 'Complete')], default=False)),
                ('last_home_screen_load', models.DateTimeField(blank=True, null=True)),
                ('interests', models.ManyToManyField(blank=True, to='base.interests')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
                ('profile_picture', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profile')),
            ],
        ),
        migrations.CreateModel(
            name='matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched', models.BooleanField(default=False)),
                ('date_matched', models.DateTimeField(default=django.utils.timezone.now)),
                ('seen', models.BooleanField(default=False)),
                ('user1_pref_days', models.CharField(blank=True, default='', max_length=100)),
                ('user2_pref_days', models.CharField(blank=True, default='', max_length=100)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dayte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayte', to='base.matches')),
            ],
        ),
        migrations.CreateModel(
            name='DailySuggestion',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='suggested', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date', models.DateField(auto_now_add=True)),
                ('suggestions', models.ManyToManyField(related_name='suggestions_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
