# Generated by Django 4.2.5 on 2023-10-13 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('travelling', 'Travelling'), ('music', 'Music'), ('sports', 'Sports'), ('reading', 'Reading'), ('movies', 'Movies'), ('cooking', 'Cooking'), ('gaming', 'Gaming'), ('photography', 'Photography'), ('dancing', 'Dancing'), ('painting', 'Painting'), ('gardening', 'Gardening'), ('writing', 'Writing'), ('fishing', 'Fishing'), ('shopping', 'Shopping'), ('hiking', 'Hiking'), ('camping', 'Camping'), ('running', 'Running'), ('swimming', 'Swimming'), ('cycling', 'Cycling'), ('yoga', 'Yoga'), ('meditation', 'Meditation'), ('singing', 'Singing'), ('acting', 'Acting'), ('learning', 'Learning'), ('volunteering', 'Volunteering'), ('socializing', 'Socializing'), ('eating', 'Eating'), ('drinking', 'Drinking'), ('sleeping', 'Sleeping'), ('partying', 'Partying'), ('clubbing', 'Clubbing'), ('gambling', 'Gambling'), ('working', 'Working'), ('studying', 'Studying')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('plan', models.CharField(blank=True, choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('prompts', models.TextField(blank=True, null=True)),
                ('finished', models.BooleanField(choices=[(False, 'Incomplete'), (True, 'Complete')], default=False)),
                ('interests', models.ManyToManyField(blank=True, to='base.interests')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profile')),
            ],
        ),
    ]
