# Generated by Django 4.2.5 on 2023-10-21 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='profile_picture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_home_screen_load',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched', models.BooleanField(default=False)),
                ('date_matched', models.DateTimeField(default=django.utils.timezone.now)),
                ('disliked', models.BooleanField(default=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailySuggestion',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='suggested', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date', models.DateField(auto_now_add=True)),
                ('suggestions', models.ManyToManyField(related_name='suggestions_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
