# Generated by Django 4.2.5 on 2023-11-06 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayte',
            name='hour',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='matches',
            name='user1_pref_times',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='matches',
            name='user2_pref_times',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dayte',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
