# Generated by Django 4.2.5 on 2023-11-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_dayte_hour_matches_user1_pref_times_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='seen',
            new_name='seen_user1',
        ),
        migrations.AddField(
            model_name='matches',
            name='seen_user2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
