# Generated by Django 4.2.5 on 2023-10-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_photo_profile_picture_profile_last_home_screen_load_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
