# Generated by Django 4.2.5 on 2023-11-06 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_seen_matches_seen_user1_matches_seen_user2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayte',
            name='id',
        ),
        migrations.AlterField(
            model_name='dayte',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dayte', serialize=False, to='base.matches'),
        ),
    ]
