# Generated by Django 4.2.5 on 2023-10-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_profile_bio_remove_profile_prompts_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='disliked',
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='free', max_length=20, null=True),
        ),
    ]
