# Generated by Django 4.2.5 on 2023-11-02 20:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_matches_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='user1_pref_days',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='matches',
            name='user2_pref_days',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.CreateModel(
            name='dayte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayte', to='base.matches')),
            ],
        ),
    ]
