# Generated by Django 4.2.5 on 2023-11-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_dayte_hour_matches_user1_pref_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='user1_pref_hours',
            new_name='user1_pref_times',
        ),
        migrations.RenameField(
            model_name='matches',
            old_name='user2_pref_hours',
            new_name='user2_pref_times',
        ),
    ]
