# Generated by Django 4.2.5 on 2023-11-05 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_user1_pref_hours_matches_user1_pref_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayte',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dayte',
            name='hour',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
