# Generated by Django 4.2.5 on 2023-09-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.CharField(blank=True, choices=[('Travelling', 'Travelling'), ('Music', 'Music'), ('Sports', 'Sports'), ('Reading', 'Reading'), ('Movies', 'Movies'), ('Cooking', 'Cooking'), ('Gaming', 'Gaming'), ('Photography', 'Photography'), ('Dancing', 'Dancing'), ('Painting', 'Painting'), ('Gardening', 'Gardening'), ('Writing', 'Writing'), ('Fishing', 'Fishing'), ('Shopping', 'Shopping'), ('Hiking', 'Hiking'), ('Camping', 'Camping'), ('Running', 'Running'), ('Swimming', 'Swimming'), ('Cycling', 'Cycling'), ('Yoga', 'Yoga'), ('Meditation', 'Meditation'), ('Singing', 'Singing'), ('Acting', 'Acting'), ('Learning', 'Learning'), ('Volunteering', 'Volunteering'), ('Socializing', 'Socializing'), ('Eating', 'Eating'), ('Drinking', 'Drinking'), ('Sleeping', 'Sleeping'), ('Partying', 'Partying'), ('Clubbing', 'Clubbing'), ('Gambling', 'Gambling'), ('Working', 'Working'), ('Studying', 'Studying')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='prompts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('free', 'free'), ('basic', 'basic'), ('premium', 'premium')], max_length=20, null=True),
        ),
    ]
