# Generated by Django 4.2.5 on 2023-09-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile_bio_profile_interests_profile_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.CharField(blank=True, choices=[('free', 'free'), ('basic', 'basic'), ('premium', 'premium')], max_length=20, null=True),
        ),
    ]
