# Generated by Django 4.2.5 on 2023-10-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_interests_remove_profile_interests_profile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='name',
            field=models.CharField(blank=True, choices=[('travelling', 'Travelling'), ('music', 'Music'), ('sports', 'Sports'), ('reading', 'Reading'), ('movies', 'Movies'), ('cooking', 'Cooking'), ('gaming', 'Gaming'), ('photography', 'Photography'), ('dancing', 'Dancing'), ('painting', 'Painting'), ('gardening', 'Gardening'), ('writing', 'Writing'), ('fishing', 'Fishing'), ('shopping', 'Shopping'), ('hiking', 'Hiking'), ('camping', 'Camping'), ('running', 'Running'), ('swimming', 'Swimming'), ('cycling', 'Cycling'), ('yoga', 'Yoga'), ('meditation', 'Meditation'), ('singing', 'Singing'), ('acting', 'Acting'), ('learning', 'Learning'), ('volunteering', 'Volunteering'), ('socializing', 'Socializing'), ('eating', 'Eating'), ('drinking', 'Drinking'), ('sleeping', 'Sleeping'), ('partying', 'Partying'), ('clubbing', 'Clubbing'), ('gambling', 'Gambling'), ('working', 'Working'), ('studying', 'Studying')], max_length=100, null=True),
        ),
    ]
